# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


BOX_IMAGE = "ubuntu/focal64"
NODE_COUNT = 2 

Vagrant.configure("2") do |config|
  config.vm.define "node0" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "node0"
    subconfig.vm.network :private_network, ip: "10.0.0.10"
 end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
    end
  end

  # Install avahi on all machines  
  config.vm.provision "shell", inline: <<-SHELL
     sudo echo "10.0.0.11 node1 " >> /etc/hosts 
     sudo echo "10.0.0.12 node2 " >> /etc/hosts 
     sudo echo "10.0.0.10 node0 " >> /etc/hosts
     sudo apt-get install curl gnupg -y 
     curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc | sudo apt-key add -
     sudo apt-key adv --keyserver "hkps://keys.openpgp.org" --recv-keys "0x0A9AF2115F4687BD29803A206B73A36E6026DFCA"
     sudo apt-get install apt-transport-https
     sudo touch /etc/apt/sources.list.d/bintray.erlang.list
     sudo echo "deb https://dl.bintray.com/rabbitmq-erlang/debian focal erlang" >> /etc/apt/sources.list.d/bintray.erlang.list
     sudo echo "deb https://dl.bintray.com/rabbitmq/debian bionic main" >> /etc/apt/sources.list.d/bintray.erlang.list
     sudo apt-get update -y
     sudo apt-get update
     sudo apt-get update -y
     sudo apt-get install rabbitmq-server -y --fix-missing
     sudo systemctl enable rabbitmq-server
     sudo systemctl start rabbitmq-server
     sudo chmod 600 /var/lib/rabbitmq/.erlang.cookie
     sudo echo "PLEASE_GENERATE_A_SECURE_VALUE" > /var/lib/rabbitmq/.erlang.cookie
     sudo bash -c  'echo "vm_memory_high_watermark.relative = 0.9" > /etc/rabbitmq/rabbitmq.conf'
     # sudo bash -c  'echo "cluster_partition_handling = pause_minority" >> /etc/rabbitmq/rabbitmq.conf'
     sudo bash -c  'echo "queue_master_locator = min-masters " >> /etc/rabbitmq/rabbitmq.conf'
     sudo systemctl restart rabbitmq-server
     sudo systemctl enable rabbitmq-server
     sleep 5
     sudo rabbitmq-plugins enable rabbitmq_management
     sudo rabbitmqctl stop_app
     sudo rabbitmqctl reset
     sudo rabbitmqctl join_cluster rabbit@node0
     sudo rabbitmqctl start_app	
     sudo rabbitmqctl add_user test test
     sudo rabbitmqctl set_user_tags test administrator
     sudo rabbitmqctl set_permissions -p / test ".*" ".*" ".*"
     SHELL
end



