# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


BOX_IMAGE = "opensuse/openSUSE-15.0-x86_64"
NODE_COUNT = 1 

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "node0"
    subconfig.vm.network :private_network, ip: "10.0.0.10"
 end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
    end
  end

  # Install avahi on all machines  
  config.vm.provision "shell", inline: <<-SHELL
     sudo echo "10.0.0.11 node1 " >> /etc/hosts 
     sudo echo "10.0.0.12 node2 " >> /etc/hosts 
     sudo echo "10.0.0.10 node0 " >> /etc/hosts 
     sudo zypper addrepo -f https://download.opensuse.org/repositories/network:/messaging:/amqp/openSUSE_Leap_15/network:messaging:amqp.repo
     sudo zypper addrepo -f http://download.opensuse.org/repositories/devel:/languages:/erlang:/Factory/openSUSE_Leap_15.0/devel:languages:erlang:Factory.repo
     sudo zypper --gpg-auto-import-keys refresh
     sudo zypper -n install erlang
     sudo zypper -n install rabbitmq-server
     sudo zypper -n install rabbitmq-server-plugins
     sudo rm /etc/rabbitmq/rabbitmq-env.conf
     mkdir -p /etc/systemd/system/epmd.socket.d/
     touch /etc/systemd/system/epmd.socket.d/ports.conf
     cat >/etc/systemd/system/epmd.socket.d/ports.conf <<EOF
      [Socket]
      # unset all ports defined in the global file, in our case this is 127.0.0.1:4369
      ListenStream=
      # add our new ports
      ListenStream=[::]:4369
      FreeBind=true
EOF
     sudo systemctl enable rabbitmq-server
     sudo systemctl start rabbitmq-server
     sudo chmod 600 /var/lib/rabbitmq/.erlang.cookie
     sudo echo "PLEASE_GENERATE_A_SECURE_VALUE" > /var/lib/rabbitmq/.erlang.cookie
     sudo bash -c  'echo "vm_memory_high_watermark.relative = 0.9" > /etc/rabbitmq/rabbitmq.conf'
     # sudo bash -c  'echo "cluster_partition_handling = pause_minority" >> /etc/rabbitmq/rabbitmq.conf'
     sudo bash -c  'echo "queue_master_locator = min-masters " >> /etc/rabbitmq/rabbitmq.conf'
     sudo systemctl restart rabbitmq-server
     sudo systemctl enable rabbitmq-server
     sudo rabbitmq-plugins enable rabbitmq_management
     sudo rabbitmqctl stop_app
     sudo rabbitmqctl reset
     sudo rabbitmqctl join_cluster rabbit@node0
     sudo rabbitmqctl start_app	
     sudo rabbitmqctl add_user test test
     sudo rabbitmqctl set_user_tags test administrator
     sudo rabbitmqctl set_permissions -p / test ".*" ".*" ".*"
     SHELL
end



