name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and export
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: myimage:latest
        outputs: type=docker,dest=/tmp/myimage.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: myimage
        path: /tmp/myimage.tar
