#!/bin/bash
export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
#helm install --name rmq-ha -f rabbitmq-ha_values.yaml stable/rabbitmq-ha
helm install --name rmq-ha -f rabbitmq-ha_values.yaml ~/git/personal/charts/stable/rabbitmq-ha/
