#!/bin/bash
export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
export POD_NAME=$(kubectl get pods --namespace default -l "app=grafana,release=graf" -o jsonpath="{.items[0].metadata.name}")
     kubectl --namespace default port-forward $POD_NAME 3000

