#!/bin/bash
sudo docker pull rabbitmq:3.8.0-alpine
kind load docker-image rabbitmq:3.8.0-alpine
sudo docker pull prom/alertmanager:v0.18.0
kind load docker-image prom/alertmanager:v0.18.0
sudo docker pull grafana/grafana:6.3.4
kind load docker-image grafana/grafana:6.3.4

